CREATE TABLE VEM_SER.ESTUDANTE(
id_estudante NUMBER NOT NULL,
nome VARCHAR2(200) NOT NULL,
data_nascimento DATE NOT NULL,
nr_matricula NUMBER(10) NOT NULL,
ativo CHAR NOT NULL,
PRIMARY KEY(id_estudante)
);

CREATE SEQUENCE seq_estudante
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

INSERT INTO VEM_SER.ESTUDANTE 
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Monkey D. Luffy', TO_DATE('05-05-2002', 'dd-mm-yyyy'), 1253, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Son Goku', TO_DATE('09/05/1976', 'dd-mm-yyyy'), 1210, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Gon Freecs', TO_DATE('05-05-2007', 'dd-mm-yyyy'), 1300, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Asta', TO_DATE('04-10-2004', 'dd-mm-yyyy'), 2253, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Midoriya Izuku', TO_DATE('15-07-2005', 'dd-mm-yyyy'), 2153, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Sakura Kinomoto', TO_DATE('01-04-2008', 'dd-mm-yyyy'), 1293, 'S');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Serena Tsukino', TO_DATE('30-06-2006', 'dd-mm-yyyy'), 1953, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Emma', TO_DATE('22-08-2008', 'dd-mm-yyyy'), 3987, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Tanjiro Kamado', TO_DATE('14-07-2004', 'dd-mm-yyyy'), 3692, 'N');

INSERT INTO VEM_SER.ESTUDANTE
(ID_ESTUDANTE, NOME, DATA_NASCIMENTO, NR_MATRICULA, ATIVO)
VALUES(SEQ_ESTUDANTE.nextval, 'Yuuji Itadori', TO_DATE('20-03-2006', 'dd-mm-yyyy'), 3700, 'S');

SELECT * FROM VEM_SER.ESTUDANTE;




